@extends('layouts.app') @section('title','Team member details')
@section('content')<div class="page-heading"><div><div class="eyebrow">YOUR TEAM</div><h1>{{ $employee->exists?'Edit team member':'Add a team member' }}</h1></div><a class="btn btn-outline-secondary" href="{{ route($prefix.'.employees.index') }}">Back to team</a></div>
<form class="panel form-panel" method="POST" action="{{ $employee->exists?route($prefix.'.employees.update',$employee):route($prefix.'.employees.store') }}">@csrf @if($employee->exists)@method('PUT')@endif<div class="form-grid">
@foreach(['name'=>'Full name','email'=>'Email address'] as $name=>$label)<div class="field"><label class="form-label" for="{{ $name }}">{{ $label }}</label><input id="{{ $name }}" name="{{ $name }}" class="form-control" value="{{ old($name,$employee->user?->$name) }}" type="{{ $name==='email'?'email':'text' }}" required></div>@endforeach
@if(!$employee->exists && $prefix==='admin')<div class="field"><label class="form-label" for="company_id">Company</label><select class="form-select" id="company_id" name="company_id" required>@foreach($companies as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></div>@endif
<div class="field"><label class="form-label" for="role">Role</label><select class="form-select" id="role" name="role">@foreach(['Manager','Staff'] as $role)<option @selected(old('role',$employee->user?->getRoleNames()->first())===$role)>{{ $role }}</option>@endforeach</select></div>
@foreach(['phone'=>'Phone','position'=>'Position'] as $name=>$label)<div class="field"><label class="form-label" for="{{ $name }}">{{ $label }}</label><input id="{{ $name }}" name="{{ $name }}" class="form-control" value="{{ old($name,$employee->$name) }}"></div>@endforeach
@if($employee->exists)<div class="field"><label class="form-label" for="status">Access status</label><select id="status" name="status" class="form-select">@foreach(['active','inactive','suspended'] as $s)<option @selected(old('status',$employee->status)===$s)>{{ $s }}</option>@endforeach</select></div>@else
@foreach(['password'=>'Initial password','password_confirmation'=>'Confirm password'] as $name=>$label)<div class="field"><label class="form-label" for="{{ $name }}">{{ $label }}</label><input id="{{ $name }}" name="{{ $name }}" type="password" class="form-control" required minlength="12" autocomplete="new-password"></div>@endforeach
<p class="muted span-2">Use at least 12 characters with uppercase, lowercase and a number. For a password-free handoff, use Invitations instead.</p>@endif</div>
<div class="form-actions"><button class="btn btn-primary">Save team member</button></div></form>@endsection
