@extends('layouts.app')
@section('title','Overview')
@section('content')
<div class="page-heading"><div><div class="eyebrow">YOUR BUSINESS, AT A GLANCE</div><h1>Welcome back, {{ explode(' ',auth()->user()->name)[0] }}.</h1><p>Here’s what’s happening in {{ auth()->user()->company->name }}.</p></div><a href="{{ route('crm.deals.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-2"></i>New opportunity</a></div>
<div class="metrics">
@foreach([['Total contacts',number_format($contacts),'Relationships in your workspace','people'],['Open opportunities',number_format($openDeals),'Deals moving through your pipeline','kanban'],['Pipeline value',number_format($pipeline,2),config('saas.currency').' · open deals','graph-up-arrow'],['Won revenue',number_format($won,2),config('saas.currency').' · all won deals','trophy']] as [$label,$value,$note,$icon])
<div class="metric {{ $loop->index===2?'highlight':'' }}"><div class="metric-label">{{ $label }}<i class="bi bi-{{ $icon }}"></i></div><div class="metric-value">{{ $value }}</div><div class="metric-note">{{ $note }}</div></div>@endforeach</div>
<div class="dashboard-grid"><section class="panel"><div class="panel-header"><h2>Opportunity pipeline</h2><a href="{{ route('crm.deals') }}">View pipeline <i class="bi bi-arrow-right"></i></a></div><p class="muted">Number of deals at each stage</p>
@foreach(['new'=>'New','qualified'=>'Qualified','proposal'=>'Proposal','won'=>'Won','lost'=>'Lost'] as $key=>$label)<div class="pipeline-row"><span>{{ $label }}</span><div class="pipeline-track"><span style="width:{{ $stages->sum('total')?($stages->get($key)?->total??0)/$stages->sum('total')*100:0 }}%"></span></div><strong>{{ $stages->get($key)?->total??0 }}</strong></div>@endforeach
@if($stages->isEmpty())<p class="muted">Add your first opportunity to start tracking progress.</p>@endif</section>
<section class="panel"><div class="panel-header"><h2>Next on your list</h2><a href="{{ route('crm.tasks') }}">All tasks</a></div>@forelse($tasks as $task)<div class="task-row"><div><strong>{{ $task->title }}</strong><small>{{ $task->assignee?->name ?? 'Unassigned' }} · {{ $task->due_date->format('M j') }}</small></div><span class="badge {{ $task->due_date->lt(today())?'badge-warning':'badge-neutral' }}">{{ $task->due_date->lt(today())?'Overdue':'Upcoming' }}</span></div>@empty<div class="empty"><i class="bi bi-check2-circle"></i><strong>A clear schedule</strong>Add a follow-up to keep your next conversation moving.</div>@endforelse</section></div>
<section class="panel"><div class="panel-header"><h2>Recently added contacts</h2><a href="{{ route('crm.contacts') }}">View all contacts <i class="bi bi-arrow-right"></i></a></div><div class="table-responsive"><table class="table"><thead><tr><th>Contact</th><th>Organization</th><th>Status</th><th>Added</th></tr></thead><tbody>@forelse($recent as $c)<tr><td><a href="{{ route('crm.contacts.edit',$c) }}"><strong>{{ $c->name }}</strong></a><small>{{ $c->email }}</small></td><td>{{ $c->organization ?: '—' }}</td><td><span class="badge">{{ $c->status }}</span></td><td>{{ $c->created_at->format('M j, Y') }}</td></tr>@empty<tr><td colspan="4"><div class="empty"><strong>Your relationships start here</strong><a href="{{ route('crm.contacts.create') }}">Add your first contact</a></div></td></tr>@endforelse</tbody></table></div></section>
@endsection
