@extends('layouts.app') @section('title','Opportunity details')
@section('content')<div class="page-heading"><div><div class="eyebrow">PIPELINE</div><h1>{{ $deal->exists?'Opportunity details':'Your next opportunity' }}</h1><p>Give your team a clear next step.</p></div><a href="{{ route('crm.deals') }}" class="btn btn-outline-secondary">Back to pipeline</a></div>
<form class="panel form-panel" method="POST" action="{{ $deal->exists?route('crm.deals.update',$deal):route('crm.deals.store') }}">@csrf @if($deal->exists)@method('PUT')@endif<div class="form-grid">
<div class="field span-2"><label class="form-label" for="title">Opportunity name</label><input id="title" name="title" class="form-control" required maxlength="160" value="{{ old('title',$deal->title) }}"></div>
<div class="field"><label class="form-label" for="value">Value ({{ config('saas.currency') }})</label><input id="value" name="value" class="form-control" type="number" min="0" step="0.01" required value="{{ old('value',$deal->value??0) }}"></div>
<div class="field"><label class="form-label" for="stage">Stage</label><select class="form-select" name="stage" id="stage">@foreach(['new','qualified','proposal','won','lost'] as $s)<option @selected(old('stage',$deal->stage??'new')===$s)>{{ $s }}</option>@endforeach</select></div>
<div class="field"><label class="form-label" for="contact_id">Contact</label><select class="form-select" name="contact_id" id="contact_id"><option value="">No linked contact</option>@foreach($contacts as $c)<option value="{{ $c->id }}" @selected(old('contact_id',$deal->contact_id)==$c->id)>{{ $c->name }}</option>@endforeach</select></div>
<div class="field"><label class="form-label" for="assigned_to">Owner</label><select class="form-select" name="assigned_to" id="assigned_to"><option value="">Unassigned</option>@foreach($users as $u)<option value="{{ $u->id }}" @selected(old('assigned_to',$deal->assigned_to)==$u->id)>{{ $u->name }}</option>@endforeach</select></div>
<div class="field"><label class="form-label" for="expected_close">Expected close</label><input class="form-control" type="date" name="expected_close" id="expected_close" value="{{ old('expected_close',$deal->expected_close?->format('Y-m-d')) }}"></div>
<div class="field span-2"><label class="form-label" for="notes">Conversation notes</label><textarea class="form-control" id="notes" name="notes" rows="5">{{ old('notes',$deal->notes) }}</textarea></div></div><div class="form-actions"><button class="btn btn-primary">Save opportunity</button><a class="btn btn-outline-secondary" href="{{ route('crm.deals') }}">Cancel</a></div></form>
@if($deal->exists)@hasanyrole('Company Admin|Manager')<form method="POST" class="mt-3" action="{{ route('crm.deals.destroy',$deal) }}" data-confirm="Remove this opportunity?">@csrf @method('DELETE')<button class="btn btn-link text-danger">Delete opportunity</button></form>@endhasanyrole @endif @endsection
